[general]
import = [
    "~/.config/alacritty/themes/themes/gruvbox_dark.toml"
]

[window]
  opacity = 0.8

[font]
size = 12.0

[font.bold]
family = "JetBrainsMonoNerdFont"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMonoNerdFont"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMonoNerdFont"
style = "Italic"

[font.normal]
family = "JetBrainsMonoNerdFont"
style = "Monospace"

[font.offset]
x = 0
y = 1

[scrolling]
history = 5000

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 6
y = 6

